### PR TITLE
Created a functional AFK system

### PR DESCRIPTION
**Pull request by ImNimboss**
Made it using a dict that stores the AFK peoples' ID as a key and the reason as a value

### CODE REVIEW

**Comment by ImNimboss** [comment]
someone answer this smh my head

**Comment by MarzaElise** [comment]
ok

**Comment by MarzaElise** [comment]
not sure if we need an afk command tho

**Comment by ImNimboss** [comment]
I see, wouldn't it be cool to have though?

**Comment by oliiiiiiiiiiiii** [comment]
Bob is gonna take over the bot soon so idk if it is necessary, will look up on it soon.

**Pull request closed without merging**
